variables:
    SolutionBaseName: 'NCS.DSS.ActionPlan'
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v0.0.3
    endpoint: 'GitHub (CDH)'

jobs:
# Test the branch name, the output of this job will satisfy the condition of one or neither of the subsequent jobs
- job: TestBranchName
  displayName: TestBranchName
  pool: Continuous Integration 02 - SSD - 160ACU

  steps:
  - task: PowerShell@2
    name: ExecuteTestBranchNameScript
    displayName: Test-BranchName
    inputs:
     targetType: 'filePath'
     filePath: 'Resources/PSScripts/Test-BranchName.ps1'
     arguments: '-BranchName $(Build.SourceBranchName) -Verbose'

# Build the app with the dfc-dotnetframework-build template.  Runs if the output of TestBranchName is Version1
- job: BuildDotNetFramework
  displayName: Build-DotNetFramework
  dependsOn: TestBranchName
  condition: and(succeeded(), eq(dependencies.TestBranchName.outputs['ExecuteTestBranchNameScript.FunctionAppVersion'], 'Version1'))
  pool:
    name: Continuous Integration 02 - SSD - 160ACU
    demands:
    - msbuild
    - visualstudio

  steps:
  - template: AzureDevOpsTemplates/Build/dfc-dotnetframework-build.yml@dfc-devops
    parameters:
      SolutionBaseName: $(SolutionBaseName)
      BuildPlatform: $(BuildPlatform)
      BuildConfiguration: $(BuildPlatform)

# Build the app with the dfc-dotnetcore-build template.  Runs if the output of TestBranchName is Version2+
# TESTING V2
- job: BuildDotNetStandard
  displayName: Build-DotNetStandard
  dependsOn: TestBranchName
  condition: and(succeeded(), eq(dependencies.TestBranchName.outputs['ExecuteTestBranchNameScript.FunctionAppVersion'], 'Version2+'))
  pool:
    name: Continuous Integration 02 - SSD - 160ACU
    demands:
    - msbuild
    - visualstudio

  steps:
  - template: AzureDevOpsTemplates/Build/dfc-dotnetcore-build-notests.yml@dfc-devops
    parameters:
      SolutionBaseName: $(SolutionBaseName)
      BuildPlatform: $(BuildPlatform)
      BuildConfiguration: $(BuildPlatform)




